services:
  blockhead:
    image: vivienbcr/blockhead:latest
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./config.yaml:/app/config.yaml
    entrypoint: [ "/app/blockhead", "-c", "config.yaml" ]
    restart: always
volumes:
  config.yaml: {}
