name: Build & test

on:
  push:
    branches: ["master", "develop", "feature/*"]
  pull_request:
    branches: ["master", "develop", "feature/*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal

      - uses: Swatinem/rust-cache@v2

      - run: |
          cargo check
          cargo test --verbose
        working-directory: tests
        env:
          ETHEREUM_NODE_URL: ${{ secrets.ETHEREUM_NODE_URL }}
          BITCOIN_NODE_URL: ${{ secrets.BITCOIN_NODE_URL }}
          TEZOS_NODE_URL: ${{ secrets.TEZOS_NODE_URL }}
          EWF_NODE_URL: ${{ secrets.EWF_NODE_URL }}
          BLOCKCYPHER_URL: ${{ secrets.BLOCKCYPHER_URL }}
